export const UPDATE_LOCALES = 'UPDATE_LOCALES';
export const UPDATE_LOCALE_MESSAGES = 'UPDATE_LOCALE_MESSAGES';
export const CHANGE_LOCALE_MESSAGES = 'CHANGE_LOCALE_MESSAGES';


export const LocaleAction = {
  UPDATE_LOCALES: UPDATE_LOCALES,
  UPDATE_LOCALE_MESSAGES: UPDATE_LOCALE_MESSAGES,
  CHANGE_LOCALE_MESSAGES: CHANGE_LOCALE_MESSAGES,
};

